service: 'serverless-coffee-talk-etincelle'

provider:
  name: aws
  runtime: nodejs14.x
  region: 'eu-west-1'
  lambdaHashingVersion: 20201221
  environment:
    S3_BUCKET_NAME: serverless-coffee-talk-etincelle

package:
  exclude:
    - "**/*"
  include:
    - templates/lambdas/translator.js

functions:
  ${file(./templates/api.yml)}

resources:
  - ${file(./templates/static-website.yml)}
  - ${file(./templates/iam.yml)}